WebApplicationTraining/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using WebApplicationTraining.Models;

namespace WebApplicationTraining.Controllers
{
    public class CategoriesController : Controller
    {
		// GET: Categories
		private ApplicationDbContext _context;
		public CategoriesController()
		{
			_context = new ApplicationDbContext();
		}
		
		[HttpGet]
		public ActionResult Index()
		{
			var categories = _context.Categories.ToList();
			return View(categories);
		}

		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Category category)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_context.Categories.Any(p => p.Name.Contains(category.Name)))
			{
				ModelState.AddModelError("Name", "Category Name Already Exists.");
				return View();
			}

			var newCategory = new Category
			{
				Name = category.Name,
				Description = category.Description,


			};

			_context.Categories.Add(newCategory);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			var categoryInDb = _context.Categories.SingleOrDefault(p => p.Id == id);

			if (categoryInDb == null)
			{
				return HttpNotFound();
			}

			_context.Categories.Remove(categoryInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			var categoryInDb = _context.Categories.SingleOrDefault(p => p.Id == id);

			if (categoryInDb == null)
			{
				return HttpNotFound();
			}

			return View(categoryInDb);
		}

		[HttpPost]
		public ActionResult Edit(Category category)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			var categoryInDb = _context.Categories.SingleOrDefault(p => p.Id == category.Id);

			if (categoryInDb == null)
			{
				return HttpNotFound();
			}
			categoryInDb.Name = category.Name;
			categoryInDb.Description = category.Description;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

WebApplicationTraining/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationTraining.Models;
using WebApplicationTraining.ViewModels;

namespace WebApplicationTraining.Controllers
{
    public class CoursesController : Controller
    {
		// GET: Courses
		private ApplicationDbContext _context;
		public CoursesController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Staff
		[HttpGet]
		public ActionResult Index(string searchString)
		{
			var courses = _context.Courses
			.Include(p => p.Category);//.Include(c => c.Topic);

			if (!String.IsNullOrEmpty(searchString))
			{
				courses = courses.Where(
					s => s.Name.Contains(searchString) ||
					s.Category.Name.Contains(searchString));
					//s.Topic.Name.Contains(searchString));

			}

			return View(courses.ToList());
		}

		[HttpGet]
		[Authorize(Roles = "TrainingStaff")]
		public ActionResult Create()
		{
			var viewModel = new CourseCategoryViewModel
			{
				Categories = _context.Categories.ToList(),
				//Topics = _context.Topics.ToList()
			};
			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "TrainingStaff")]
		public ActionResult Create(Course course)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_context.Courses.Any(p => p.Name.Contains(course.Name)))
			{
				ModelState.AddModelError("Name", "Course Name Already Exists.");
				return View();
			}

			var newCourse = new Course
			{
				Name = course.Name,
				CategoryId = course.CategoryId,
				TopicId = 11,
			};

			_context.Courses.Add(newCourse);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "TrainingStaff")]

		public ActionResult Delete(int id)
		{
			var courseInDb = _context.Courses.SingleOrDefault(p => p.Id == id);

			if (courseInDb == null)
			{
				return HttpNotFound();
			}

			_context.Courses.Remove(courseInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "TrainingStaff")]

		public ActionResult Edit(int id)
		{
			var courseInDb = _context.Courses.SingleOrDefault(p => p.Id == id);

			if (courseInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new CourseCategoryViewModel
			{
				Course = courseInDb,
				Categories = _context.Categories.ToList(),
				//Topics = _context.Topics.ToList()
			};

			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "TrainingStaff")]

		public ActionResult Edit(Course course)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			var courseInDb = _context.Courses.SingleOrDefault(p => p.Id == course.Id);

			if (courseInDb == null)
			{
				return HttpNotFound();
			}

			courseInDb.Name = course.Name;
			courseInDb.CategoryId = course.CategoryId;
			//courseInDb.TopicId = course.TopicId;
			_context.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

WebApplicationTraining/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplicationTraining.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplicationTraining/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using WebApplicationTraining.Models;

namespace WebApplicationTraining.Controllers
{
    public class TopicsController : Controller
    {
		// GET: Topics
		private ApplicationDbContext _context;
		public TopicsController()
		{
			_context = new ApplicationDbContext();
		}
		
		[HttpGet]
		public ActionResult Index()
		{
			var topics = _context.Topics.ToList();
			return View(topics);
		}

		[HttpGet]
		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(Topic topic)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_context.Topics.Any(p => p.Name.Contains(topic.Name)))
			{
				ModelState.AddModelError("Name", "Topic Name Already Exists.");
				return View();
			}

			var newTopic = new Topic
			{
				Name = topic.Name,
				Description = topic.Description,


			};

			_context.Topics.Add(newTopic);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			var topicInDb = _context.Topics.SingleOrDefault(p => p.Id == id);

			if (topicInDb == null)
			{
				return HttpNotFound();
			}

			_context.Topics.Remove(topicInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{
			var topicInDb = _context.Topics.SingleOrDefault(p => p.Id == id);

			if (topicInDb == null)
			{
				return HttpNotFound();
			}

			return View(topicInDb);
		}

		[HttpPost]
		public ActionResult Edit(Topic topic)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			var topicInDb = _context.Topics.SingleOrDefault(p => p.Id == topic.Id);

			if (topicInDb == null)
			{
				return HttpNotFound();
			}
			topicInDb.Name = topicInDb.Name;
			topicInDb.Description = topicInDb.Description;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

WebApplicationTraining/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplicationTraining/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplicationTraining/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<br/>
<br />


<div class="navbar-collapse collapse">
        <h1>WELCOME TO </h1>
        <h2>FPT APPLICATION TRAINING</h2>
    
        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
        {
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("ManageUsers", "UsersWithRoles", "ManageUsers", null, new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Profile Admin", "Profile", "ManageUsers", null, new { @class = "btn btn-default" })</li>
            </ul>
                }
        @if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
        {
            
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Manage Account", "Index", "ManagerStaffViewModels", null, new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Manage Category", "Index", "Categories", null, new { @class = "btn btn-default" })</li>
                <!--<li>@Html.ActionLink("Manage Topics", "Index", "Topics", null, new { @class = "btn btn-default" })</li>-->
                <li>@Html.ActionLink("Manage Courses", "Index", "Courses", null, new { @class = "btn btn-default" })</li>
                <!--<li>@Html.ActionLink("Assign Trainer Topic", "Index", "TrainerTopics", null, new { @class = "btn btn-default" })</li>-->
                <li>@Html.ActionLink("Assign Trainee Course", "Index", "TraineeCourses", null, new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Assign Trainer Course", "Index", "TrainerCourses", null, new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Profile Training Staff", "Profile", "ManageUsers", null, new { @class = "btn btn-default" })</li>
            </ul>
                

         }
        @if (Request.IsAuthenticated && User.IsInRole("Trainer"))
        {

            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Trainer Course", "Index", "TrainerCourses", null, new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Profile Trainer", "Profile", "ManageUsers", null, new { @class = "btn btn-default" })</li>
            </ul>
        }
        @if (Request.IsAuthenticated && User.IsInRole("Trainee"))
        {
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Trainee Courses", "Index", "TraineeCourses", null, new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Profile Trainee", "Profile", "ManageUsers", null, new { @class = "btn btn-default" })</li>
            </ul>
        }
    



</div>