WebApplicationTraining/Controllers/TrainerCoursesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationTraining.Models;
using System.Data.Entity;
using WebApplicationTraining.ViewModels;

namespace WebApplicationTraining.Controllers
{
    public class TrainerCoursesController : Controller
    {
        private ApplicationDbContext _context;
        public TrainerCoursesController()
        {
            _context = new ApplicationDbContext();
        }
        public ActionResult Index()
        {
            if (User.IsInRole("TrainingStaff"))
            {
                var trainercourses = _context.TrainerCourses.Include(t => t.Course).Include(t =>t.Trainer).ToList();
                return View(trainercourses);
            }
            if (User.IsInRole("Trainer"))
            {
                var trainerId = User.Identity.GetUserId();
                var Res = _context.TrainerCourses.Where(e => e.TrainerId == trainerId).Include(t => t.Course).ToList();
                return View(Res);
            }
            return View("Login");
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff")]

        public ActionResult Delete(int id)
        {
            var courseInDb = _context.TrainerCourses.SingleOrDefault(p => p.Id == id);

            if (courseInDb == null)
            {
                return HttpNotFound();
            }
            _context.TrainerCourses.Remove(courseInDb);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {

            var role = (from r in _context.Roles where r.Name.Contains("Trainer") select r).FirstOrDefault();
            var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(role.Id)).ToList();

            var courses = _context.Courses.ToList();

            var TrainerCourseVM = new TrainerCourseViewModel()
            {
                Courses = courses,
                Trainers = users,
                TrainerCourse = new TrainerCourse()
            };

            return View(TrainerCourseVM);
        }

        [HttpPost]
        public ActionResult Create(TrainerCourseViewModel model)
        {
            //get trainer
            var role = (from r in _context.Roles where r.Name.Contains("Trainee") select r).FirstOrDefault();
            var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(role.Id)).ToList();

            var courses = _context.Courses.ToList();


            if (ModelState.IsValid)
            {
                _context.TrainerCourses.Add(model.TrainerCourse);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            var TrainerCourseVM = new TrainerCourseViewModel()
            {
                Courses = courses,
                Trainers = users,
                TrainerCourse = new TrainerCourse()
            };

            return View(TrainerCourseVM);
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Edit(int id)
        {
            var role = (from r in _context.Roles where r.Name.Contains("Trainer") select r).FirstOrDefault();
            var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(role.Id)).ToList();
            var courses = _context.Courses.ToList();
            var trainercourseId = _context.TrainerCourses.SingleOrDefault(n => n.Id == id);
            if (trainercourseId == null) return HttpNotFound();
            var viewModel = new TrainerCourseViewModel()
            {
                Courses = courses,
                Trainers = users,
                TrainerCourse = new TrainerCourse()
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Edit(TrainerCourseViewModel model)
        {
            var role = (from r in _context.Roles where r.Name.Contains("Trainer") select r).FirstOrDefault();
            var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(role.Id)).ToList();
            var courses = _context.Courses.ToList();

            if (!ModelState.IsValid) return View();
            var TraineeCourseVM = new TrainerCourseViewModel()
            {
                Courses = courses,
                Trainers = users,
                TrainerCourse = new TrainerCourse()
            };
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplicationTraining/Views/TrainerCourses/Create.cshtml
@model WebApplicationTraining.ViewModels.TrainerCourseViewModel
@{
    ViewBag.Title = "Create Assign Trainer To Course";
}

<h2>Create Assign Trainer To Course</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Assign Trainer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TrainerCourse.Trainer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.TrainerCourse.TrainerId, new SelectList(Model.Trainers, "Id", "UserName"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainerCourse.TrainerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrainerCourse.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.TrainerCourse.CourseId, new SelectList(Model.Courses, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainerCourse.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Assign" class="btn btn-default" />
            </div>
        </div>
    </div>
 }

WebApplicationTraining/Views/TrainerCourses/Edit.cshtml
@model WebApplicationTraining.ViewModels.TrainerCourseViewModel
@{
    ViewBag.Title = "Edit Assign Traier To Course";
}

<h2>Edit Assign Traiee To Course</h2>
@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm("Edit", "TrainerCourses", FormMethod.Post))
{
    @Html.HiddenFor(u => u.TrainerCourse.Id)

    <div class="form-group">
        @Html.LabelFor(u => u.TrainerCourse.Trainer, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DropDownListFor(x => x.TrainerCourse.TrainerId,
            new SelectList(Model.Trainers, "Id", "UserName"),
            "Select User", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TrainerCourse.Course, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.DropDownListFor(x => x.TrainerCourse.CourseId,
            new SelectList(Model.Courses, "Id", "Name"),
            "Select Courses", new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
}
<br />
@Html.ActionLink("Back Index", "Index", null, new { @class = "btn btn-default" })

WebApplicationTraining/Views/TrainerCourses/Index.cshtml
@model IEnumerable<WebApplicationTraining.Models.TrainerCourse>
@{
    ViewBag.Title = "Assign Trainer to Course";
}


@if (User.IsInRole("TrainingStaff"))
{
    <h2>Assign Trainer To Course</h2>
    <p>
        @Html.ActionLink("Assign Trainer to Course", "Create", null, new { @class = "btn btn-default" })
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Trainer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course)
            </th>
            <th>
            </th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Trainer.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Category)
                </td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })</td>
            </tr>
        }
    </table>
}
@if (User.IsInRole("Trainer"))
{
    <h2>Courses Assigned</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(item => item.Course)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Course.Name)</td>

            </tr>
        }
    </table>
}
@Html.ActionLink("Back to home", "Index", "Home", null, new { @class = "btn btn-primary" })