WebApplicationTraining/Controllers/ManageUsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplicationTraining.Models;
using WebApplicationTraining.ViewModels;
using static WebApplicationTraining.Controllers.AccountController;
using static WebApplicationTraining.Controllers.ManageController;

namespace WebApplicationTraining.Controllers
{
    public class ManageUsersController : Controller
    {
        private ApplicationDbContext _context;
        public ManageUsersController()
        {
            _context = new ApplicationDbContext();
        }
        
        public ActionResult UsersWithRoles()
        {
            var usersWithRoles = (from user in _context.Users
                                  select new
                                  {
                                      UserId = user.Id,
                                      Name = user.Name,
                                      Age = user.Age,
                                      WorkingPlace = user.WorkingPlace,
                                      Username = user.UserName,
                                      Emailaddress = user.Email,
                                      Password = user.PasswordHash,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in _context.Roles on userRole.RoleId
                                                   equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => new Users_In_Role()

                                  {
                                      UserId = p.UserId,
                                      Name = p.Name,
                                      Username = p.Username,
                                      Email = p.Emailaddress,
                                      Role = string.Join(",", p.RoleNames)
                                  });


            return View(usersWithRoles);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var appUser = _context.Users.Find(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            return View(appUser);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(ApplicationUser user)
        {
            var userInDb = _context.Users.Find(user.Id);

            if (userInDb == null)
            {
                return View(user);
            }

            if (ModelState.IsValid)
            {
                userInDb.Name = user.Name;
                userInDb.UserName = user.UserName;
                userInDb.Age = user.Age;
                userInDb.WorkingPlace = user.WorkingPlace;
                userInDb.Phone = user.Phone;
                userInDb.Email = user.Email;


                _context.Users.AddOrUpdate(userInDb);
                _context.SaveChanges();

                return RedirectToAction("UsersWithRoles");
            }
            return View(user);
        }
        [Authorize(Roles = "Admin, Trainer")]
        public ActionResult Details(string id)
        {
            if (id == null) return HttpNotFound();
            var userDetail = _context.Users.SingleOrDefault(t => t.Id == id);
            if (userDetail == null) return HttpNotFound();
            return View(userDetail);
        }
        [Authorize(Roles = "Admin,Trainer,Trainee,TrainingStaff")]
        public ActionResult Profile()
        {
            var userProfileId = User.Identity.GetUserId();
            if (userProfileId == null) return HttpNotFound();
            var userProfile = _context.Users.SingleOrDefault(p => p.Id == userProfileId);
            return View(userProfile);
        }
        [HttpGet]
        [Authorize(Roles = "Admin,Trainer, Trainee,TrainingStaff")]
        public ActionResult EditProfile(string id)
        {
            id = User.Identity.GetUserId();
            if (id == null) return HttpNotFound();
            var userInfo = _context.Users.Find(id);
            if (userInfo == null) return HttpNotFound();
            return View(userInfo);
        }
        [HttpPost]
        [Authorize(Roles = "Admin,Trainer, Trainee,TrainingStaff")]
        public ActionResult EditProfile(ApplicationUser user)
        {
            user.Id = User.Identity.GetUserId();
            var userProfile = _context.Users.Find(user.Id);
            if (userProfile == null) return View(user);
            if (ModelState.IsValid)
            {
                userProfile.Name = user.Name;
                userProfile.UserName = user.UserName;
                userProfile.Age = user.Age;
                userProfile.WorkingPlace = user.WorkingPlace;
                userProfile.Phone = user.Phone;
                userProfile.Email = user.Email;
                _context.Users.AddOrUpdate(userProfile);
                _context.SaveChanges();

                return RedirectToAction("Profile");
            }
            return View(user);

        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            var userInDb = _context.Users.SingleOrDefault(p => p.Id == id);

            if (userInDb == null)
            {
                return HttpNotFound();
            }
            _context.Users.Remove(userInDb);
            _context.SaveChanges();

            return RedirectToAction("UsersWithRoles");

        }
    }
}

WebApplicationTraining/Views/ManageUsers/Details.cshtml
@model WebApplicationTraining.Models.ApplicationUser
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<br />
<div class="panel panel-primary">
    <div class="panel-heading">Information of Users</div>
    <div class="panel-body">
        <p>Full Name: @Model.Name</p>
        <p>User Name: @Model.UserName</p>
        <p>Age: @Model.Age</p>
        <p>Working Place: @Model.WorkingPlace</p>
        <p>Email: @Model.Email</p>
        <p>Phone: @Model.Phone</p>
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "UsersWithRoles", null, new { @class = "btn btn-primary" })
</div>

WebApplicationTraining/Views/ManageUsers/Edit.cshtml
@model WebApplicationTraining.Models.ApplicationUser
@{ ViewBag.Title = "Edit"; }

<h2>Edit</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm("Edit", "ManageUsers", FormMethod.Post))
{
    @Html.HiddenFor(u => u.Id)
    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(u => u.Name)
            @Html.EditorFor(u => u.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.UserName)
            @Html.EditorFor(u => u.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.UserName, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.Age)
            @Html.EditorFor(u => u.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Age, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.WorkingPlace)
            @Html.EditorFor(u => u.WorkingPlace, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.WorkingPlace, "", new { @class = "text-danger" })
        </div>  
        <div class="form-group">
            @Html.LabelFor(u => u.Email)
            @Html.EditorFor(u => u.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.Phone)
            @Html.EditorFor(u => u.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Phone, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>}

<div>
@Html.ActionLink("Back to List", "UsersWithRoles",null,new { @class = "btn btn-primary"})
</div>

WebApplicationTraining/Views/ManageUsers/EditProfile.cshtml
@model WebApplicationTraining.Models.ApplicationUser
@{
    ViewBag.Title = "EditProfile";
}

<h2>Edit Profile</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm("EditProfile", "ManageUsers", FormMethod.Post))
{
    @Html.HiddenFor(u => u.Id)
    <div class="form-horizontal">
        <h4>Account</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(u => u.Name)
            @Html.EditorFor(u => u.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.UserName)
            @Html.EditorFor(u => u.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.UserName, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.Age)
            @Html.EditorFor(u => u.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Age, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.WorkingPlace)
            @Html.EditorFor(u => u.WorkingPlace, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.WorkingPlace, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.Email)
            @Html.EditorFor(u => u.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(u => u.Phone)
            @Html.EditorFor(u => u.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.Phone, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            
                <input type="submit" value="Save" class="btn btn-default" />
           
        </div>
    </div>
   
 
}
<br/>

<div>
    @Html.ActionLink("Back to Profile", "Profile", null, new { @class = "btn btn-primary" }) @Html.ActionLink("Reset Manager Password", "ResetPassword", "Account", @Model.Id, new { @class = "btn btn-default" })
</div>

WebApplicationTraining/Views/ManageUsers/Profile.cshtml
@model WebApplicationTraining.Models.ApplicationUser
@{
    ViewBag.Title = "Profile";
}

<h2>Profile</h2>

<div class="panel panel-primary">
    <div class="panel-heading">Information of Users</div>
    <div class="panel-body">
        <p>Full Name: @Model.Name</p>
        <p>User Name: @Model.UserName</p>
        <p>Age: @Model.Age</p>
        <p>Working Place: @Model.WorkingPlace</p>
        <p>Email: @Model.Email</p>
        <p>Phone: @Model.Phone</p>
        @Html.ActionLink("Edit Profile", "EditProfile", null, new { @class = "btn btn-danger" })
    </div>
    
</div>
    
<br/>
    @Html.ActionLink("Back to Home", "Index","Home", null, new { @class = "btn btn-primary" })

WebApplicationTraining/Views/ManageUsers/UsersWithRoles.cshtml
@model IEnumerable<WebApplicationTraining.ViewModels.Users_In_Role>

@{ 
    ViewBag.Title = "UsersWithRoles"; 
}
<br/>

@if (Request.IsAuthenticated && User.IsInRole("Admin"))
{
    <p>
        <a onclick="window.location='@Url.Action("Register", "Account")'" class="btn btn-primary btn-lg">New User </a>
    </p>}
<h3>Account</h3>
<div class="panel-body">
    <table class="table table-striped" id="UsersWithRoles">
        <thead>
            <tr>
                <th>Name</th>
                <th>UserName</th>
                <th>Email</th>
                <th>Role</th>
                <th>Edit</th>
                <th>Details</th>
                <th>Delete</th>
            </tr>
        </thead>
        @foreach (var user in Model)
        {
            <tr>
                @if ((user.Role.Contains("Staff") || user.Role.Contains("Trainee") || user.Role.Contains("Trainer")) == true)
                {
                    <td>@user.Name</td>
                    <td>@user.Username</td>
                    <td>@user.Email</td>
                    <td>@user.Role</td>
                    <td>@Html.ActionLink("Edit", "Edit", new { id = user.UserId },new { @class="btn btn-default"})</td>
                    <td>@Html.ActionLink("Details", "Details", new { id = user.UserId }, new { @class = "btn btn-default" })</td>
                    <td>@Html.ActionLink("Delete", "Delete", new { id = user.UserId }, new { @class = "btn btn-danger" })</td>
                }

            </tr>
        }
    </table>
</div>

<div>
</div>

@section scripts{
    <script>
        $(function () {
            $('#UsersWithRoles').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": true
            });
        });</script>
}
@Html.ActionLink("Back to home", "Index", "Home",null,new { @class = "btn btn-primary" })