WebApplicationTraining/Models/TrainerTopic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplicationTraining.Models
{
    public class TrainerTopic
    {
        public int Id { get; set; }
        public string TrainerId { get; set; }
        public int TopicId { get; set; }
        public int Course { get; set; }

        public ApplicationUser Trainer { get; set; }
        public Topic Topic { get; set; }
    }
}

WebApplicationTraining/ViewModels/TrainerTopicViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplicationTraining.Models;

namespace WebApplicationTraining.ViewModels
{
    public class TrainerTopicViewModel
    {
        public TrainerTopic TrainerTopic { get; set; }
        public IEnumerable<ApplicationUser> Trainers { get; set; }
        public IEnumerable<Topic> Topics { get; set; }
    }
}

WebApplicationTraining/Controllers/TrainerTopicsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationTraining.Models;
using WebApplicationTraining.ViewModels;
using System.Data.Entity;
using System.Data.Entity.Migrations;

namespace WebApplicationTraining.Controllers
{
    public class TrainerTopicsController : Controller
    {
        private ApplicationDbContext _context;

        public TrainerTopicsController()
        {
            _context = new ApplicationDbContext();
        }
        [Authorize(Roles = "TrainingStaff , Trainer")]
        public ActionResult Index()
        {
            if (User.IsInRole("TrainingStaff"))
            {
                var trainertopics = _context.TrainerTopics
                  .Include(t => t.Topic)
                  .Include(t => t.Trainer)
                  .ToList();
                return View(trainertopics);
            }

            if (User.IsInRole("Trainer"))
            {
                var trainerId = User.Identity.GetUserId();
                var Res = _context.TrainerTopics
                  .Where(e => e.TrainerId == trainerId)
                  .Include(t => t.Topic)
                  .ToList();
                return View(Res);
            }
            return View("Login");
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff")]

        public ActionResult Delete(int id)
        {
            var courseInDb = _context.TrainerTopics.SingleOrDefault(p => p.Id == id);

            if (courseInDb == null)
            {
                return HttpNotFound();
            }
            _context.TrainerTopics.Remove(courseInDb);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "TrainingStaff")]
        [HttpGet]
        public ActionResult Create()
        {
            var role = (from r in _context.Roles
                        where r.Name.Contains("Trainer")
                        select r)
                        .FirstOrDefault();
            var users = _context.Users
              .Where(x => x.Roles
              .Select(y => y.RoleId)
              .Contains(role.Id))
              .ToList();

            var topics = _context.Topics.ToList();

            var TrainerTopicVM = new TrainerTopicViewModel()
            {
                Topics = topics,
                Trainers = users,
                TrainerTopic = new TrainerTopic()
            };

            return View(TrainerTopicVM);
        }

        [HttpPost]
        public ActionResult Create(TrainerTopicViewModel model)
        {
            var role = (from r in _context.Roles
                        where r.Name.Contains("Trainer")
                        select r)
                        .FirstOrDefault();
            var users = _context.Users
              .Where(x => x.Roles
              .Select(y => y.RoleId)
              .Contains(role.Id))
              .ToList();

            var topics = _context.Topics.ToList();
            if (!ModelState.IsValid)
            {
                return View();
            }

            var trainerTopics = _context.TrainerTopics.ToList();
            var topicId = model.TrainerTopic.TopicId;

            var checkTrainerInTopic = trainerTopics
              .SingleOrDefault(c => c.TopicId == topicId && c.TrainerId == model.TrainerTopic.TrainerId);

            if (checkTrainerInTopic != null)
            {
                ModelState.AddModelError("Name", "Trainer Topic Already Exists.");
                var TrainerTopicVM = new TrainerTopicViewModel()
                {
                    Topics = topics,
                    Trainers = users,
                    TrainerTopic = new TrainerTopic()
                };
                return View(TrainerTopicVM);
            }
            _context.TrainerTopics.Add(model.TrainerTopic);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var trainertopicInDb = _context.TrainerTopics.SingleOrDefault(p => p.Id == id);
            if (trainertopicInDb == null)
            {
                return HttpNotFound();
            }
            return View(trainertopicInDb);
        }

        [HttpPost]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Edit(TrainerTopic trainertopic)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var trainertopicInDb = _context.TrainerTopics.SingleOrDefault(p => p.Id == trainertopic.Id);

            if (trainertopicInDb == null)
            {
                return HttpNotFound();
            }
            trainertopicInDb.Trainer = trainertopic.Trainer;
            trainertopicInDb.Topic = trainertopic.Topic;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplicationTraining/Views/TrainerTopics/Create.cshtml
@model WebApplicationTraining.ViewModels.TrainerTopicViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Assign Trainer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TrainerTopic.TrainerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.TrainerTopic.TrainerId, new SelectList(Model.Trainers, "Id", "UserName"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainerTopic.TrainerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrainerTopic.TopicId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.TrainerTopic.TopicId, new SelectList(Model.Topics, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrainerTopic.TopicId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Assign" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebApplicationTraining/Views/TrainerTopics/Edit.cshtml
@model WebApplicationTraining.Models.TrainerTopic
@{
    ViewBag.Title = "Edit Assign Trainer T";
}

<h2>Edit</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm("Edit", "TrainerTopics", FormMethod.Post))
{
    @Html.HiddenFor(u => u.Id)
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(u => u.Trainer.Name)
            @Html.DropDownListFor(u => u.TrainerId,new SelectList(Model.TrainerId, "Id", "Name"),"Select Trainer",new { @class = "form-control" })
            
        </div>
        <div class="form-group">
            @Html.LabelFor(u => u.Topic)
            @Html.EditorFor(u => u.TopicId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(u => u.TopicId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@Html.ActionLink("Back to Index", "Index", null, new { @class = "btn btn-default" })

WebApplicationTraining/Views/TrainerTopics/Index.cshtml
@model IEnumerable<WebApplicationTraining.Models.TrainerTopic>
@{
    ViewBag.Title = "Assign Trainer To Topic";
}



@if (User.IsInRole("Trainer"))
{
<h2>Topic Assigned</h2>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(item => item.Topic)
            </th>

            <th>

            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Topic.Name)
                </td>

            </tr>
        }
    </table>
}
@if (User.IsInRole("TrainingStaff"))
{
    <h2>Topic</h2>
    <p>
        @Html.ActionLink("Assign Trainer To Topic", "Create", null, new { @class = "btn btn-primary"})
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Trainer)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Topic)
            </th>
            <!--<th>Edit</th>-->
            <th>Delete</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Trainer.UserName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Topic.Name)
                </td>

                <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })</td>
            </tr>
        }

    </table>
}
@Html.ActionLink("Back to home", "Index", "Home", null, new { @class = "btn btn-primary" })